// GENERATED by tools/port-knight-scene.mjs — DO NOT hand-edit.
// Source: themes/knight-dragon/KnightDragonScene.dc.html (Claude Design project
// eef274a5-697b-4bc4-a885-8a5b6ea5ce39 / KnightDragonScene.dc.html).
// To update the scene: pull the latest design file, replace the source,
// re-run the generator. Hand-editing this file is how v23 drifted.

export const KEYFRAMES = `
@keyframes kdFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}
@keyframes kdFlapA{0%,100%{transform:rotate(-4deg)}50%{transform:rotate(-26deg)}}
@keyframes kdFlapB{0%,100%{transform:rotate(4deg)}50%{transform:rotate(24deg)}}
@keyframes kdFlick{0%,100%{transform:scale(1);opacity:.9}50%{transform:scale(1.12,.84);opacity:1}}
@keyframes kdTwinkle{0%,100%{opacity:.25}50%{opacity:1}}
@keyframes kdSmoke{0%{transform:translateY(0) scale(.5);opacity:0}14%{opacity:.88}100%{transform:translateY(-250px) scale(3.2);opacity:0}}
@keyframes kdFlag{0%,100%{transform:skewX(0deg) scaleX(1)}50%{transform:skewX(-9deg) scaleX(.92)}}
`;

export const STAGE_MARKUP = `<g data-kd="stage" transform="translate(0,52) scale(0.8333333)">
  <defs>
    <linearGradient id="kdHorizonGrad" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" style="stop-color:var(--horizon);stop-opacity:0"></stop>
      <stop offset=".42" style="stop-color:var(--horizon);stop-opacity:1"></stop>
    </linearGradient>
  </defs>
  <!-- SKY: celestial disc + twinkles -->
  <circle cx="130" cy="90" r="66" style="fill:var(--celest);opacity:.28"></circle>
  <circle cx="130" cy="90" r="48" style="fill:var(--celest);opacity:.9"></circle>
  <circle cx="288" cy="68" r="2.5" style="fill:var(--particle);animation:kdTwinkle 2.6s ease-in-out infinite"></circle>
  <circle cx="504" cy="114" r="2" style="fill:var(--particle);animation:kdTwinkle 3.1s ease-in-out .4s infinite"></circle>
  <circle cx="792" cy="53" r="2.5" style="fill:var(--particle);animation:kdTwinkle 2.2s ease-in-out .9s infinite"></circle>
  <circle cx="1056" cy="99" r="2" style="fill:var(--particle);animation:kdTwinkle 2.8s ease-in-out .6s infinite"></circle>
  <!-- COUNTRYSIDE (verbatim; overflow stays hidden like the design's svg —
       the rising smoke dissolves at the countryside's top edge) -->
  <svg x="0" y="120" width="1200" height="640" viewBox="0 0 1200 640" preserveAspectRatio="none" style="overflow:hidden">
    <!-- far hills -->
    <path d="M0 240 Q170 165 360 214 Q460 244 540 198 Q610 162 690 198 Q820 250 950 194 Q1080 158 1200 204 L1200 640 L0 640 Z" style="fill:var(--hill-far)"></path>
    <!-- CASTLE over the knight's right shoulder -->
    <g transform="translate(214,20)">
      <rect x="556" y="182" width="104" height="30" style="fill:var(--castle)"></rect>
      <rect x="560" y="150" width="24" height="60" style="fill:var(--castle)"></rect>
      <rect x="632" y="142" width="24" height="68" style="fill:var(--castle)"></rect>
      <rect x="586" y="126" width="46" height="86" style="fill:var(--castle-2)"></rect>
      <path d="M560 150 l12 -15 l12 15 z" style="fill:var(--castle-2)"></path>
      <path d="M632 142 l12 -16 l12 16 z" style="fill:var(--castle-2)"></path>
      <path d="M586 126 l23 -20 l23 20 z" style="fill:var(--castle)"></path>
      <g style="fill:var(--castle)"><rect x="556" y="174" width="13" height="10"></rect><rect x="579" y="174" width="13" height="10"></rect><rect x="647" y="174" width="13" height="10"></rect></g>
      <g style="fill:var(--window-lit)"><rect x="595" y="150" width="8" height="13" rx="2"></rect><rect x="609" y="150" width="8" height="13" rx="2"></rect><rect x="565" y="166" width="7" height="11" rx="2"></rect></g>
      <g style="stroke:var(--castle-2);stroke-width:2.6"><line x1="572" y1="135" x2="572" y2="114"></line><line x1="609" y1="106" x2="609" y2="83"></line></g>
      <g style="fill:var(--flag)">
        <path d="M572 115 l16 5 l-16 5 z" style="transform-origin:572px 120px;animation:kdFlag 2.6s ease-in-out infinite"></path>
        <path d="M609 85 l17 5 l-17 5 z" style="transform-origin:609px 90px;animation:kdFlag 2.3s ease-in-out .5s infinite"></path>
      </g>
      <ellipse data-kd="smoke" cx="644" cy="128" rx="12" ry="22" style="fill:var(--smoke);transform-origin:644px 148px;animation:kdSmoke 3.4s ease-in .4s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="650" cy="128" rx="9" ry="17" style="fill:var(--smoke);transform-origin:650px 148px;animation:kdSmoke 4.1s ease-in 1.5s infinite"></ellipse>
      <g data-kd="fire" style="transform-origin:644px 152px;animation:kdFlick .3s ease-in-out infinite">
        <path d="M644 128 q13 15 9 26 q-2 9 -9 13 q-7 -4 -9 -13 q-3 -11 9 -26 z" style="fill:var(--fire-1)"></path>
        <path d="M644 140 q6 8 4 14 q-1 5 -4 7 q-3 -2 -4 -7 q-1 -6 4 -14 z" style="fill:var(--fire-2)"></path>
      </g>
    </g>
    <!-- SHIRE A (high, far hill) -->
    <g data-kd="shire">
      <rect x="262" y="238" width="26" height="20" style="fill:var(--house)"></rect><path d="M259 238 l16 -13 l16 13 z" style="fill:var(--roof)"></path>
      <rect x="290" y="230" width="34" height="26" style="fill:var(--house-2)"></rect><path d="M286 230 l21 -16 l21 16 z" style="fill:var(--roof)"></path><rect x="312" y="236" width="7" height="7" style="fill:var(--window-lit)"></rect>
      <rect x="326" y="240" width="22" height="18" style="fill:var(--house)"></rect><path d="M323 240 l14 -11 l14 11 z" style="fill:var(--roof-2)"></path>
      <rect x="300" y="214" width="28" height="20" style="fill:var(--house)"></rect><path d="M297 214 l17 -13 l17 13 z" style="fill:var(--roof)"></path>
      <rect x="350" y="244" width="26" height="18" style="fill:var(--house-2)"></rect><path d="M347 244 l16 -12 l16 12 z" style="fill:var(--roof-2)"></path>
      <rect x="240" y="252" width="20" height="15" style="fill:var(--house)"></rect><path d="M237 252 l13 -10 l13 10 z" style="fill:var(--roof-2)"></path>
      <rect x="336" y="220" width="20" height="15" style="fill:var(--house-2)"></rect><path d="M333 220 l13 -10 l13 10 z" style="fill:var(--roof)"></path>
    </g>
    <!-- mid hills -->
    <path d="M0 352 Q240 275 520 340 Q800 400 1060 320 Q1140 305 1200 340 L1200 640 L0 640 Z" style="fill:var(--hill-mid)"></path>
    <!-- SHIRE B (mid hill) -->
    <g data-kd="shire">
      <rect x="418" y="338" width="24" height="18" style="fill:var(--house)"></rect><path d="M415 338 l15 -12 l15 12 z" style="fill:var(--roof-2)"></path>
      <rect x="444" y="326" width="40" height="26" style="fill:var(--house)"></rect><path d="M440 326 l24 -18 l24 18 z" style="fill:var(--roof)"></path><rect x="470" y="332" width="8" height="8" style="fill:var(--window-lit)"></rect>
      <rect x="488" y="332" width="30" height="22" style="fill:var(--house-2)"></rect><path d="M484 332 l19 -14 l19 14 z" style="fill:var(--roof-2)"></path>
      <rect x="462" y="350" width="26" height="18" style="fill:var(--house)"></rect><path d="M459 350 l16 -12 l16 12 z" style="fill:var(--roof)"></path>
      <rect x="504" y="348" width="24" height="16" style="fill:var(--house)"></rect><path d="M501 348 l15 -11 l15 11 z" style="fill:var(--roof-2)"></path>
      <rect x="430" y="356" width="22" height="15" style="fill:var(--house-2)"></rect><path d="M427 356 l14 -10 l14 10 z" style="fill:var(--roof)"></path>
      <rect x="478" y="316" width="22" height="16" style="fill:var(--house)"></rect><path d="M475 316 l14 -11 l14 11 z" style="fill:var(--roof-2)"></path>
    </g>
    <!-- SHIRE D (mid-right) -->
    <g data-kd="shire">
      <rect x="600" y="404" width="28" height="20" style="fill:var(--house)"></rect><path d="M597 404 l17 -13 l17 13 z" style="fill:var(--roof)"></path>
      <rect x="628" y="392" width="40" height="26" style="fill:var(--house-2)"></rect><path d="M624 392 l24 -18 l24 18 z" style="fill:var(--roof)"></path><rect x="654" y="398" width="8" height="8" style="fill:var(--window-lit)"></rect>
      <rect x="672" y="400" width="30" height="22" style="fill:var(--house)"></rect><path d="M668 400 l19 -14 l19 14 z" style="fill:var(--roof-2)"></path>
      <rect x="646" y="418" width="26" height="18" style="fill:var(--house-2)"></rect><path d="M643 418 l16 -12 l16 12 z" style="fill:var(--roof)"></path>
      <rect x="612" y="430" width="24" height="16" style="fill:var(--house)"></rect><path d="M609 430 l15 -11 l15 11 z" style="fill:var(--roof-2)"></path>
      <rect x="684" y="424" width="22" height="16" style="fill:var(--house-2)"></rect><path d="M681 424 l14 -11 l14 11 z" style="fill:var(--roof)"></path>
    </g>
    <!-- near hills -->
    <path d="M0 452 Q240 414 490 456 Q740 502 1000 446 Q1110 420 1200 448 L1200 640 L0 640 Z" style="fill:var(--hill-near)"></path>
    <!-- SHIRE C (low, near hill) -->
    <g data-kd="shire">
      <rect x="300" y="452" width="30" height="22" style="fill:var(--house)"></rect><path d="M296 452 l19 -15 l19 15 z" style="fill:var(--roof)"></path>
      <rect x="332" y="440" width="42" height="30" style="fill:var(--house-2)"></rect><path d="M328 440 l25 -19 l25 19 z" style="fill:var(--roof)"></path><rect x="358" y="447" width="9" height="9" style="fill:var(--window-lit)"></rect>
      <rect x="378" y="448" width="30" height="24" style="fill:var(--house)"></rect><path d="M374 448 l19 -15 l19 15 z" style="fill:var(--roof-2)"></path>
      <rect x="350" y="466" width="26" height="18" style="fill:var(--house)"></rect><path d="M347 466 l16 -12 l16 12 z" style="fill:var(--roof)"></path>
      <rect x="412" y="458" width="24" height="18" style="fill:var(--house-2)"></rect><path d="M409 458 l15 -12 l15 12 z" style="fill:var(--roof-2)"></path>
      <rect x="286" y="470" width="20" height="15" style="fill:var(--house)"></rect><path d="M283 470 l13 -10 l13 10 z" style="fill:var(--roof-2)"></path>
    </g>
    <!-- front hill -->
    <path d="M0 548 Q320 514 640 544 Q920 564 1200 530 L1200 640 L0 640 Z" style="fill:var(--hill-front)"></path>
    <!-- TREES clustered between the villages (far -> near) -->
    <g style="fill:var(--hill-mid);opacity:.7">
      <path d="M150 214 l11 -24 l11 24 z"></path><path d="M170 210 l9 -20 l9 20 z"></path><path d="M198 218 l10 -22 l10 22 z"></path>
      <path d="M406 236 l10 -22 l10 22 z"></path><path d="M424 232 l9 -19 l9 19 z"></path>
      <path d="M900 200 l11 -22 l11 22 z"></path><path d="M1030 206 l10 -22 l10 22 z"></path><path d="M1052 210 l9 -18 l9 18 z"></path><path d="M1075 208 l9 -19 l9 19 z"></path>
    </g>
    <g style="fill:var(--tree);opacity:.9">
      <rect x="378" y="352" width="7" height="16"></rect><path d="M367 356 l14 -30 l14 30 z"></path><path d="M373 344 l11 -24 l11 24 z"></path>
      <rect x="398" y="356" width="6" height="14"></rect><path d="M388 360 l13 -27 l13 27 z"></path>
      <rect x="546" y="346" width="7" height="16"></rect><path d="M535 350 l14 -30 l14 30 z"></path>
      <rect x="566" y="350" width="6" height="14"></rect><path d="M556 354 l13 -27 l13 27 z"></path><path d="M562 342 l10 -22 l10 22 z"></path>
      <rect x="580" y="352" width="6" height="14"></rect><path d="M570 356 l12 -26 l12 26 z"></path>
      <rect x="742" y="348" width="7" height="16"></rect><path d="M731 352 l14 -30 l14 30 z"></path>
      <rect x="762" y="352" width="6" height="14"></rect><path d="M752 356 l13 -27 l13 27 z"></path>
      <rect x="998" y="340" width="7" height="16"></rect><path d="M987 344 l14 -30 l14 30 z"></path><path d="M1005 348 l11 -24 l11 24 z"></path>
    </g>
    <g style="fill:var(--tree)">
      <rect x="150" y="452" width="8" height="20"></rect><path d="M137 458 l17 -34 l17 34 z"></path><path d="M144 444 l12 -28 l12 28 z"></path>
      <rect x="176" y="456" width="7" height="18"></rect><path d="M164 462 l16 -32 l16 32 z"></path>
      <rect x="452" y="470" width="8" height="20"></rect><path d="M439 476 l17 -34 l17 34 z"></path><path d="M446 462 l12 -28 l12 28 z"></path>
      <rect x="480" y="474" width="7" height="18"></rect><path d="M468 480 l16 -32 l16 32 z"></path>
      <rect x="524" y="468" width="8" height="20"></rect><path d="M511 474 l17 -34 l17 34 z"></path>
      <rect x="736" y="470" width="8" height="20"></rect><path d="M723 476 l17 -34 l17 34 z"></path><path d="M730 462 l12 -28 l12 28 z"></path>
      <rect x="1084" y="446" width="8" height="20"></rect><path d="M1071 452 l17 -34 l17 34 z"></path><path d="M1079 438 l12 -28 l12 28 z"></path>
      <rect x="1112" y="450" width="7" height="18"></rect><path d="M1100 456 l16 -32 l16 32 z"></path>
    </g>
    <!-- HEAVY SMOKE + FLAME on burning houses -->
    <g>
      <ellipse data-kd="smoke" cx="307" cy="188" rx="15" ry="30" style="fill:var(--smoke);transform-origin:307px 210px;animation:kdSmoke 3.0s ease-in .0s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="314" cy="188" rx="12" ry="24" style="fill:var(--smoke);transform-origin:314px 210px;animation:kdSmoke 3.7s ease-in .8s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="301" cy="188" rx="11" ry="22" style="fill:var(--smoke);transform-origin:301px 210px;animation:kdSmoke 4.4s ease-in 1.8s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="362" cy="204" rx="12" ry="24" style="fill:var(--smoke);transform-origin:362px 224px;animation:kdSmoke 3.3s ease-in .5s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="368" cy="204" rx="10" ry="20" style="fill:var(--smoke);transform-origin:368px 224px;animation:kdSmoke 4.1s ease-in 1.5s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="464" cy="282" rx="15" ry="30" style="fill:var(--smoke);transform-origin:464px 304px;animation:kdSmoke 3.1s ease-in .3s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="471" cy="282" rx="12" ry="24" style="fill:var(--smoke);transform-origin:471px 304px;animation:kdSmoke 3.9s ease-in 1.3s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="457" cy="282" rx="11" ry="22" style="fill:var(--smoke);transform-origin:457px 304px;animation:kdSmoke 4.6s ease-in 2.2s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="648" cy="348" rx="15" ry="30" style="fill:var(--smoke);transform-origin:648px 370px;animation:kdSmoke 3.2s ease-in .6s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="655" cy="348" rx="12" ry="24" style="fill:var(--smoke);transform-origin:655px 370px;animation:kdSmoke 4.0s ease-in 1.6s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="641" cy="348" rx="11" ry="22" style="fill:var(--smoke);transform-origin:641px 370px;animation:kdSmoke 4.7s ease-in 2.5s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="353" cy="398" rx="16" ry="32" style="fill:var(--smoke);transform-origin:353px 420px;animation:kdSmoke 3.0s ease-in .2s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="361" cy="398" rx="13" ry="26" style="fill:var(--smoke);transform-origin:361px 420px;animation:kdSmoke 3.8s ease-in 1.1s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="346" cy="398" rx="11" ry="22" style="fill:var(--smoke);transform-origin:346px 420px;animation:kdSmoke 4.5s ease-in 2.1s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="600" cy="104" rx="12" ry="24" style="fill:var(--smoke);transform-origin:600px 122px;animation:kdSmoke 3.5s ease-in .4s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="606" cy="104" rx="10" ry="20" style="fill:var(--smoke);transform-origin:606px 122px;animation:kdSmoke 4.3s ease-in 1.7s infinite"></ellipse>
      <g data-kd="fire" style="transform-origin:307px 214px;animation:kdFlick .3s ease-in-out infinite"><path d="M307 190 q13 15 9 26 q-2 9 -9 13 q-7 -4 -9 -13 q-3 -11 9 -26 z" style="fill:var(--fire-1)"></path><path d="M307 202 q6 8 4 14 q-1 5 -4 7 q-3 -2 -4 -7 q-1 -6 4 -14 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:362px 228px;animation:kdFlick .27s ease-in-out .14s infinite"><path d="M362 208 q11 13 8 22 q-2 8 -8 11 q-6 -3 -8 -11 q-2 -9 8 -22 z" style="fill:var(--fire-1)"></path></g>
      <g data-kd="fire" style="transform-origin:464px 306px;animation:kdFlick .28s ease-in-out .1s infinite"><path d="M464 282 q14 16 10 28 q-2 9 -10 13 q-8 -4 -10 -13 q-3 -12 10 -28 z" style="fill:var(--fire-1)"></path><path d="M464 295 q7 9 5 15 q-1 5 -5 7 q-4 -2 -5 -7 q-2 -6 5 -15 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:648px 372px;animation:kdFlick .31s ease-in-out .2s infinite"><path d="M648 348 q14 16 10 28 q-2 9 -10 13 q-8 -4 -10 -13 q-3 -12 10 -28 z" style="fill:var(--fire-1)"></path><path d="M648 361 q7 9 5 15 q-1 5 -5 7 q-4 -2 -5 -7 q-2 -6 5 -15 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:353px 420px;animation:kdFlick .3s ease-in-out .16s infinite"><path d="M353 394 q15 17 10 30 q-2 10 -10 15 q-8 -5 -10 -15 q-3 -13 10 -30 z" style="fill:var(--fire-1)"></path><path d="M353 408 q7 9 5 17 q-1 6 -5 9 q-4 -3 -5 -9 q-2 -8 5 -17 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:600px 132px;animation:kdFlick .29s ease-in-out .16s infinite"><path d="M600 114 q10 12 7 21 q-1 7 -7 10 q-6 -3 -7 -10 q-2 -9 7 -21 z" style="fill:var(--fire-1)"></path></g>
    </g>
    <!-- burning village where the castle stood -->
    <g data-kd="shire">
      <rect x="548" y="216" width="30" height="22" style="fill:var(--house)"></rect><path d="M544 216 l19 -15 l19 15 z" style="fill:var(--roof)"></path>
      <rect x="580" y="206" width="38" height="26" style="fill:var(--house-2)"></rect><path d="M576 206 l23 -18 l23 18 z" style="fill:var(--roof)"></path><rect x="606" y="212" width="8" height="8" style="fill:var(--window-lit)"></rect>
      <rect x="620" y="214" width="28" height="20" style="fill:var(--house)"></rect><path d="M616 214 l18 -14 l18 14 z" style="fill:var(--roof-2)"></path>
      <rect x="596" y="230" width="24" height="16" style="fill:var(--house)"></rect><path d="M593 230 l15 -11 l15 11 z" style="fill:var(--roof-2)"></path>
      <rect x="534" y="230" width="20" height="15" style="fill:var(--house-2)"></rect><path d="M531 230 l13 -10 l13 10 z" style="fill:var(--roof)"></path>
      <ellipse data-kd="smoke" cx="599" cy="158" rx="15" ry="30" style="fill:var(--smoke);transform-origin:599px 182px;animation:kdSmoke 3.2s ease-in .3s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="606" cy="158" rx="12" ry="24" style="fill:var(--smoke);transform-origin:606px 182px;animation:kdSmoke 4.0s ease-in 1.4s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="560" cy="172" rx="12" ry="24" style="fill:var(--smoke);transform-origin:560px 194px;animation:kdSmoke 3.6s ease-in .8s infinite"></ellipse>
      <g data-kd="fire" style="transform-origin:599px 186px;animation:kdFlick .29s ease-in-out infinite"><path d="M599 162 q14 16 10 28 q-2 9 -10 13 q-8 -4 -10 -13 q-3 -12 10 -28 z" style="fill:var(--fire-1)"></path><path d="M599 175 q7 9 5 15 q-1 5 -5 7 q-4 -2 -5 -7 q-2 -6 5 -15 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:563px 198px;animation:kdFlick .27s ease-in-out .15s infinite"><path d="M563 178 q11 13 8 22 q-2 8 -8 11 q-6 -3 -8 -11 q-2 -9 8 -22 z" style="fill:var(--fire-1)"></path></g>
    </g>
    <!-- burning village over the knight's left shoulder -->
    <g data-kd="shire">
      <rect x="1000" y="216" width="30" height="22" style="fill:var(--house)"></rect><path d="M996 216 l19 -15 l19 15 z" style="fill:var(--roof)"></path>
      <rect x="1032" y="206" width="38" height="26" style="fill:var(--house-2)"></rect><path d="M1028 206 l23 -18 l23 18 z" style="fill:var(--roof)"></path><rect x="1058" y="212" width="8" height="8" style="fill:var(--window-lit)"></rect>
      <rect x="1072" y="214" width="28" height="20" style="fill:var(--house)"></rect><path d="M1068 214 l18 -14 l18 14 z" style="fill:var(--roof-2)"></path>
      <rect x="1048" y="230" width="24" height="16" style="fill:var(--house)"></rect><path d="M1045 230 l15 -11 l15 11 z" style="fill:var(--roof-2)"></path>
      <rect x="988" y="230" width="20" height="15" style="fill:var(--house-2)"></rect><path d="M985 230 l13 -10 l13 10 z" style="fill:var(--roof)"></path>
      <ellipse data-kd="smoke" cx="1051" cy="158" rx="15" ry="30" style="fill:var(--smoke);transform-origin:1051px 182px;animation:kdSmoke 3.3s ease-in .5s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="1058" cy="158" rx="12" ry="24" style="fill:var(--smoke);transform-origin:1058px 182px;animation:kdSmoke 4.1s ease-in 1.6s infinite"></ellipse>
      <ellipse data-kd="smoke" cx="1012" cy="172" rx="12" ry="24" style="fill:var(--smoke);transform-origin:1012px 194px;animation:kdSmoke 3.7s ease-in .9s infinite"></ellipse>
      <g data-kd="fire" style="transform-origin:1051px 186px;animation:kdFlick .3s ease-in-out .1s infinite"><path d="M1051 162 q14 16 10 28 q-2 9 -10 13 q-8 -4 -10 -13 q-3 -12 10 -28 z" style="fill:var(--fire-1)"></path><path d="M1051 175 q7 9 5 15 q-1 5 -5 7 q-4 -2 -5 -7 q-2 -6 5 -15 z" style="fill:var(--fire-2)"></path></g>
      <g data-kd="fire" style="transform-origin:1015px 198px;animation:kdFlick .28s ease-in-out .18s infinite"><path d="M1015 178 q11 13 8 22 q-2 8 -8 11 q-6 -3 -8 -11 q-2 -9 8 -22 z" style="fill:var(--fire-1)"></path></g>
    </g>
  </svg>
  <!-- HORIZON + TRAY SHELF (design z3/z4; the game's tile tray sits over it) -->
  <rect x="0" y="584" width="1200" height="176" fill="url(#kdHorizonGrad)"></rect>
  <rect x="0" y="610" width="1200" height="220" style="fill:var(--tray)"></rect>
  <rect x="0" y="610" width="1200" height="3" style="fill:var(--tray-edge)"></rect>
  <!-- DRAGON (verbatim; positioning divs → g's with div-center origins) -->
  <svg x="230" y="16" width="540" height="360" viewBox="0 0 540 360" style="overflow:visible">
    <g data-kd="dragonOuter" style="transform:translate(-800px,14px) scale(0.4);transform-origin:270px 180px">
      <g data-kd="dragonRoam" style="transform:scaleX(-1);transform-origin:270px 180px">
        <g data-kd="dragonWince" style="transform-origin:270px 180px;transition:transform .14s ease">
          <g style="animation:kdFloat 4.2s ease-in-out infinite">
              <g data-kd="dragonTint" style="transition:filter .18s ease">
                <path d="M400 224 q104 8 122 92 q-36 -6 -58 -30 q10 30 -6 50 q-32 -26 -30 -72 q-36 -6 -48 -22 z" style="fill:var(--d-body-2)"></path>
                <g style="transform-origin:342px 152px;animation:kdFlapB 1.35s ease-in-out infinite">
                  <path d="M342 152 q72 -98 172 -60 q-36 44 -86 50 q42 26 28 68 q-80 -30 -126 -62 z" style="fill:var(--d-wing-2)"></path>
                </g>
                <path d="M356 258 q6 40 -2 58 q-22 4 -26 -14 q-2 -22 8 -44 z" style="fill:var(--d-body-2)"></path>
                <ellipse cx="320" cy="206" rx="114" ry="84" style="fill:var(--d-body)"></ellipse>
                <path d="M228 240 q92 48 184 0 q-16 48 -92 52 q-76 -4 -92 -52 z" style="fill:var(--d-belly)"></path>
                <g style="fill:var(--d-horn)">
                  <path d="M244 132 l8 -30 l18 26 z"></path><path d="M286 120 l8 -30 l18 26 z"></path>
                  <path d="M330 122 l8 -28 l18 24 z"></path><path d="M376 138 l8 -26 l16 24 z"></path>
                </g>
                <path d="M286 262 q4 44 -4 62 q-24 4 -28 -16 q-2 -24 10 -46 z" style="fill:var(--d-body-2)"></path>
                <path d="M262 320 l-8 12 M274 322 l0 14 M286 320 l8 12" style="stroke:var(--d-belly);stroke-width:5;stroke-linecap:round;fill:none"></path>
                <path d="M256 152 q-98 -34 -156 6 q-8 -32 20 -50 q90 -30 156 22 z" style="fill:var(--d-body)"></path>
                <g>
                  <ellipse cx="82" cy="120" rx="54" ry="43" style="fill:var(--d-body)"></ellipse>
                  <path d="M38 116 q-26 2 -28 22 q-2 15 20 17 l32 -8 z" style="fill:var(--d-body)"></path>
                  <path d="M94 84 l6 -36 l22 28 z" style="fill:var(--d-horn)"></path>
                  <path d="M70 80 l-2 -34 l20 26 z" style="fill:var(--d-horn)"></path>
                  <path d="M118 96 q30 -10 40 10 q-24 8 -40 2 z" style="fill:var(--d-body-2)"></path>
                  <path d="M44 96 q20 -12 40 -2" style="stroke:var(--d-body-2);stroke-width:7;stroke-linecap:round;fill:none"></path>
                  <ellipse cx="66" cy="112" rx="15" ry="17" style="fill:#ffffff"></ellipse>
                  <circle cx="60" cy="115" r="7.5" style="fill:var(--d-eye)"></circle>
                  <circle cx="20" cy="126" r="4" style="fill:var(--d-body-2)"></circle>
                  <path d="M12 138 q30 10 62 4" style="stroke:var(--d-body-2);stroke-width:4;stroke-linecap:round;fill:none"></path>
                  <g data-kd="painEye" style="opacity:0;transition:opacity .1s ease">
                    <ellipse cx="66" cy="112" rx="17" ry="18" style="fill:var(--d-body)"></ellipse>
                    <path d="M54 106 l20 6 l-20 7" style="stroke:#15121a;stroke-width:5;stroke-linecap:round;stroke-linejoin:round;fill:none"></path>
                    <ellipse cx="30" cy="140" rx="11" ry="7" style="fill:#3a0f10"></ellipse>
                  </g>
                  <g data-kd="deadEye" style="opacity:0;transition:opacity .3s ease">
                    <ellipse cx="66" cy="112" rx="17" ry="18" style="fill:var(--d-body)"></ellipse>
                    <path d="M55 103 l22 20 M77 103 l-22 20" style="stroke:#15121a;stroke-width:6;stroke-linecap:round"></path>
                  </g>
                </g>
                <g style="transform-origin:362px 142px;animation:kdFlapA 1.35s ease-in-out infinite">
                  <path d="M362 142 q98 -122 204 -66 q-38 42 -94 48 q48 30 32 80 q-90 -34 -152 -66 z" style="fill:var(--d-wing)"></path>
                  <path d="M368 146 q70 -70 150 -54 M382 168 q66 -46 132 -30 M398 188 q56 -24 108 -8" style="stroke:var(--d-wing-2);stroke-width:4;fill:none;opacity:.7"></path>
                </g>
              </g>
              <!-- FIRE BREATH aimed steeply down onto the shire -->
              <g data-kd="fireBreath" style="opacity:0;transform-origin:14px 132px;transform:rotate(-78deg) scale(2.6);transition:opacity .2s ease">
                <g style="animation:kdFlick .26s ease-in-out infinite;transform-origin:12px 124px">
                  <path d="M12 120 L-20 108 L-46 116 L-70 96 L-96 108 L-126 84 L-152 96 L-176 128 L-152 160 L-126 146 L-96 156 L-70 142 L-46 150 L-20 136 L12 128 Z" style="fill:var(--fire-1)"></path>
                  <path d="M12 123 L-16 114 L-36 119 L-56 106 L-76 115 L-98 128 L-76 149 L-56 138 L-36 143 L-16 132 L12 125 Z" style="fill:var(--fire-2)"></path>
                </g>
              </g>
          </g>
        </g>
      </g>
    </g>
  </svg>
  <!-- HIT SPARK (box position ADAPTED to ride at the game's battle anchor) -->
  <svg x="565" y="305" width="150" height="150" viewBox="0 0 150 150" style="overflow:visible">
    <g data-kd="spark" style="opacity:0;transform:scale(0.4);transform-origin:75px 75px;transition:opacity .16s ease,transform .16s ease">
      <path d="M75 4 l16 46 l46 -18 l-30 40 l44 24 l-50 6 l14 48 l-40 -32 l-40 32 l14 -48 l-50 -6 l44 -24 l-30 -40 l46 18 z" style="fill:#ffd23f"></path>
      <circle cx="75" cy="75" r="26" style="fill:#ffffff"></circle>
      <circle cx="75" cy="75" r="12" style="fill:#ff6a3c"></circle>
    </g>
  </svg>
  <!-- KNIGHT (verbatim; feet on the tray top / GROUND_Y) -->
  <svg x="762" y="270" width="240" height="340" viewBox="0 0 240 340" style="overflow:visible">
      <ellipse cx="120" cy="330" rx="76" ry="13" style="fill:rgba(0,0,0,.2)"></ellipse>
      <path d="M84 150 q-40 70 -30 158 q34 8 62 0 q-8 -80 4 -158 z" style="fill:var(--k-cape)"></path>
      <path d="M92 150 q-26 66 -18 150 q18 4 30 2 q-4 -78 6 -152 z" style="fill:var(--k-cape);opacity:.55"></path>
      <rect x="98" y="256" width="22" height="86" rx="10" style="fill:var(--k-cloth-2)"></rect>
      <rect x="122" y="256" width="22" height="86" rx="10" style="fill:var(--k-cloth-2)"></rect>
      <rect x="84" y="156" width="76" height="112" rx="22" style="fill:var(--k-cloth)"></rect>
      <rect x="66" y="170" width="22" height="88" rx="11" style="fill:var(--k-cloth-2)"></rect>
      <rect x="158" y="170" width="22" height="88" rx="11" style="fill:var(--k-cloth-2)"></rect>
      <rect x="110" y="136" width="26" height="24" style="fill:var(--k-cloth)"></rect>
      <circle cx="122" cy="116" r="30" style="fill:var(--k-cloth)"></circle>
      <ellipse cx="122" cy="121" rx="18" ry="21" style="fill:var(--k-skin)"></ellipse>
      <ellipse cx="115" cy="118" rx="2.4" ry="3.2" style="fill:var(--k-ink)"></ellipse>
      <ellipse cx="129" cy="118" rx="2.4" ry="3.2" style="fill:var(--k-ink)"></ellipse>
      <path d="M110 112 q3 -3 7 -1 M126 112 q4 -3 8 -1" style="stroke:var(--k-ink);stroke-width:2;stroke-linecap:round;fill:none"></path>
      <circle cx="109" cy="127" r="3.6" style="fill:var(--k-cheek);opacity:.6"></circle>
      <circle cx="135" cy="127" r="3.6" style="fill:var(--k-cheek);opacity:.6"></circle>
      <path d="M115 129 q7 6 14 0" style="stroke:var(--k-ink);stroke-width:2.4;stroke-linecap:round;fill:none"></path>
      <g data-kd="armor1" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <path d="M92 322 h30 v14 q0 6 -6 6 h-42 q-6 0 -2 -8 z" style="fill:var(--k-metal)"></path>
        <path d="M124 322 h30 v14 q4 8 -2 8 h-42 q-6 0 -6 -6 v-14 z" style="fill:var(--k-metal)"></path>
      </g>
      <g data-kd="armor2" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <rect x="97" y="260" width="24" height="66" rx="8" style="fill:var(--k-metal-2)"></rect>
        <rect x="121" y="260" width="24" height="66" rx="8" style="fill:var(--k-metal-2)"></rect>
        <ellipse cx="109" cy="284" rx="14" ry="12" style="fill:var(--k-metal)"></ellipse>
        <ellipse cx="133" cy="284" rx="14" ry="12" style="fill:var(--k-metal)"></ellipse>
      </g>
      <g data-kd="armor3" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <path d="M82 158 q40 -14 76 0 q10 40 2 92 q-40 18 -80 0 q-8 -52 2 -92 z" style="fill:var(--k-metal)"></path>
        <path d="M120 162 l0 84" style="stroke:var(--k-metal-2);stroke-width:4"></path>
        <path d="M92 176 q28 12 56 0" style="stroke:var(--k-metal-2);stroke-width:3;fill:none"></path>
        <rect x="106" y="150" width="28" height="14" rx="7" style="fill:var(--k-metal-2)"></rect>
        <circle cx="120" cy="200" r="9" style="fill:var(--k-gem)"></circle>
        <circle cx="120" cy="200" r="4" style="fill:#ffffff;opacity:.7"></circle>
      </g>
      <g data-kd="armor4" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <path d="M86 244 q34 12 68 0 l-4 16 q-30 10 -60 0 z" style="fill:var(--k-metal-2)"></path>
        <path d="M90 258 q30 10 60 0 l-6 18 q-24 8 -48 0 z" style="fill:var(--k-metal)"></path>
      </g>
      <g data-kd="armor5" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <path d="M62 158 q22 -16 44 -2 q4 22 -6 34 q-24 8 -40 -6 q-6 -14 2 -26 z" style="fill:var(--k-metal)"></path>
        <path d="M178 158 q-22 -16 -44 -2 q-4 22 6 34 q24 8 40 -6 q6 -14 -2 -26 z" style="fill:var(--k-metal)"></path>
        <circle cx="84" cy="168" r="5" style="fill:var(--k-gem-2)"></circle>
        <circle cx="156" cy="168" r="5" style="fill:var(--k-gem-2)"></circle>
      </g>
      <g data-kd="armor6" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <rect x="64" y="212" width="24" height="46" rx="10" style="fill:var(--k-metal-2)"></rect>
        <rect x="158" y="212" width="24" height="46" rx="10" style="fill:var(--k-metal-2)"></rect>
        <circle cx="76" cy="264" r="14" style="fill:var(--k-metal)"></circle>
        <circle cx="170" cy="264" r="14" style="fill:var(--k-metal)"></circle>
      </g>
      <g data-kd="armor7" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <path d="M90 116 q2 -44 32 -44 q30 0 32 44 q-4 6 -10 8 q-22 -12 -44 0 q-6 -2 -10 -8 z" style="fill:var(--k-metal)"></path>
        <path d="M94 114 q-6 20 4 42 q7 3 11 -3 q-8 -18 -6 -38 z" style="fill:var(--k-metal-2)"></path>
        <path d="M150 114 q6 20 -4 42 q-7 3 -11 -3 q8 -18 6 -38 z" style="fill:var(--k-metal-2)"></path>
      </g>
      <g data-kd="armor8" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <rect x="101" y="104" width="42" height="7" rx="3" style="fill:var(--k-metal)"></rect>
        <rect x="119" y="107" width="6" height="20" rx="3" style="fill:var(--k-metal-2)"></rect>
        <path d="M116 78 q-4 -34 22 -46 q14 22 6 44 q-14 10 -28 2 z" style="fill:var(--k-plume)"></path>
        <path d="M120 80 q-2 -22 16 -32 q8 15 2 28 q-10 8 -18 4 z" style="fill:var(--k-plume);opacity:.6"></path>
        <circle cx="122" cy="82" r="5.5" style="fill:var(--k-gem)"></circle>
      </g>
      <g data-kd="armor10" style="opacity:0;transform:translateY(14px);transition:opacity .35s ease,transform .4s ease">
        <g transform="translate(240,0) scale(-1,1)">
          <path d="M34 176 q26 -10 56 0 v34 q0 44 -28 62 q-28 -18 -28 -62 z" style="fill:var(--k-shield)"></path>
          <path d="M62 176 v136 M34 214 q28 8 56 0" style="stroke:var(--k-shield-2);stroke-width:4;fill:none;opacity:.6"></path>
          <path d="M34 176 q26 -10 56 0 v34 q0 44 -28 62 q-28 -18 -28 -62 z" style="fill:none;stroke:var(--k-trim);stroke-width:5"></path>
          <circle cx="62" cy="216" r="9" style="fill:var(--k-gem)"></circle>
          <circle cx="62" cy="216" r="4" style="fill:#ffffff;opacity:.7"></circle>
        </g>
      </g>
      <g data-kd="armor9" style="opacity:0;transition:opacity .35s ease">
        <g transform="translate(240,0) scale(-1,1)">
          <g data-kd="swordJab" style="transform:rotate(0deg);transform-origin:170px 278px;transition:transform .16s ease">
            <rect x="164" y="242" width="12" height="34" rx="5" style="fill:#6e4a2a"></rect>
            <rect x="146" y="236" width="48" height="11" rx="5" style="fill:var(--k-trim)"></rect>
            <circle cx="170" cy="278" r="8" style="fill:var(--k-trim)"></circle>
            <circle cx="170" cy="278" r="3.5" style="fill:var(--k-gem)"></circle>
            <path d="M164 242 L164 92 L170 76 L176 92 L176 242 Z" style="fill:#eef3fb"></path>
            <rect x="169" y="96" width="2" height="146" style="fill:var(--k-metal-2)"></rect>
          </g>
        </g>
      </g>
  </svg>
</g>`;
