// GENERATED by tools/port-monkey-scene.mjs — DO NOT hand-edit.
// Source: themes/monkey/{MonkeyScene,Monkey,Monkey Game Flow}.dc.html
// (Claude Design project fe16e7c1-b1f1-4853-bdb3-49851d87eaf1).
// To update the scene: pull the latest design files, replace the sources,
// re-run the generator. Hand-editing this file is how a port drifts.

export const KEYFRAMES = `
@keyframes mkSwayA{0%,100%{transform:rotate(-2.2deg)}50%{transform:rotate(2.4deg)}}
@keyframes mkSwayB{0%,100%{transform:rotate(1.8deg)}50%{transform:rotate(-2deg)}}
@keyframes mkVine{0%,100%{transform:rotate(-1.8deg)}50%{transform:rotate(1.8deg)}}
@keyframes mkWing{0%,100%{transform:scaleX(1)}50%{transform:scaleX(.4)}}
@keyframes mkFly1{0%{transform:translate(0,0)}50%{transform:translate(34px,-26px)}100%{transform:translate(0,0)}}
@keyframes mkFly2{0%{transform:translate(0,0)}50%{transform:translate(-30px,-20px)}100%{transform:translate(0,0)}}
@keyframes mkTwinkle{0%,100%{opacity:.2}50%{opacity:1}}
@keyframes mkFire{0%{opacity:.2;transform:translate(0,0)}50%{opacity:1;transform:translate(-16px,-22px)}100%{opacity:.2;transform:translate(0,0)}}
@keyframes mkRay{0%,100%{opacity:.28}50%{opacity:.55}}
@keyframes mkGlow{0%,100%{opacity:.55;transform:scale(1)}50%{opacity:.8;transform:scale(1.04)}}
@keyframes mkbBob{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}
@keyframes mkbBlink{0%,90%,100%{transform:scaleY(1)}95%{transform:scaleY(.1)}}
@keyframes mkbTail{0%,100%{transform:rotate(-4deg)}50%{transform:rotate(5deg)}}
@keyframes mkbSwing{0%,100%{transform:rotate(-7deg)}50%{transform:rotate(7deg)}}
@keyframes mkbSpark{0%,100%{transform:scale(.7);opacity:.5}50%{transform:scale(1.15);opacity:1}}
@keyframes mkbChompA{0%{transform:scaleY(.5)}18%{transform:scaleY(1)}66%{transform:scaleY(1)}82%{transform:scaleY(.1)}100%{transform:scaleY(.28)}}
@keyframes mkbChompB{0%{transform:scaleY(.5)}18%{transform:scaleY(1)}66%{transform:scaleY(1)}82%{transform:scaleY(.1)}100%{transform:scaleY(.28)}}
@keyframes mkPop{0%{transform:translate(-50%,-50%) scale(0)}62%{transform:translate(-50%,-50%) scale(1.22)}100%{transform:translate(-50%,-50%) scale(1)}}
@keyframes mkReactA{0%,100%{transform:translateY(0) scale(1)}42%{transform:translateY(-15px) scale(1.05,.95)}}
@keyframes mkReactB{0%,100%{transform:translateY(0) scale(1)}42%{transform:translateY(-15px) scale(1.05,.95)}}
@keyframes mkEatA{0%{left:52%;top:32%;transform:translate(-50%,-50%) scale(.8);opacity:0}18%{opacity:1}60%{left:71%;top:54%;transform:translate(-50%,-50%) rotate(20deg) scale(1.05)}82%{left:73%;top:57%;transform:translate(-50%,-50%) scale(1)}100%{left:73%;top:57%;transform:translate(-50%,-50%) scale(0);opacity:1}}
@keyframes mkEatB{0%{left:52%;top:32%;transform:translate(-50%,-50%) scale(.8);opacity:0}18%{opacity:1}60%{left:71%;top:54%;transform:translate(-50%,-50%) rotate(20deg) scale(1.05)}82%{left:73%;top:57%;transform:translate(-50%,-50%) scale(1)}100%{left:73%;top:57%;transform:translate(-50%,-50%) scale(0);opacity:1}}
@keyframes mkSwingRig{0%{transform:translateX(4%) rotate(3deg)}12%{transform:translateX(-24%) rotate(-27deg)}26%{transform:translateX(-58%) rotate(24deg)}40%{transform:translateX(-96%) rotate(-24deg)}54%{transform:translateX(-58%) rotate(23deg)}68%{transform:translateX(-24%) rotate(-20deg)}82%{transform:translateX(-6%) rotate(14deg)}100%{transform:translateX(0) rotate(0deg)}}
@keyframes mkVineSway{0%,100%{transform:rotate(-3.5deg)}50%{transform:rotate(3.5deg)}}
@keyframes mkBanner{0%{transform:translateY(-130%)}70%{transform:translateY(6%)}100%{transform:translateY(0)}}
@keyframes mkSparkle{0%,100%{transform:scale(.6);opacity:.4}50%{transform:scale(1.15);opacity:1}}
@keyframes mkBigPop{0%{transform:scale(.4);opacity:0}55%{transform:scale(1.18)}100%{transform:scale(1);opacity:1}}
`;

export const STAGE_MARKUP = `<g data-mk="stage" transform="translate(0,52) scale(0.8333333)">
  <defs>
    <radialGradient id="mkVignette" cx="0.5" cy="0.42" r="0.62">
      <stop offset="0.56" data-mk="vstop-in" style="stop-color:#080c22;stop-opacity:0"></stop>
      <stop offset="1" data-mk="vstop-out" style="stop-color:#080c22;stop-opacity:1"></stop>
    </radialGradient>
  </defs>
  <!-- BACKGROUND: MonkeyScene, verbatim (baked monkey cut; bananas + day/night now interactive) -->
  <defs>
    <radialGradient id="mkWarmGlow" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0" style="stop-color:#ffe6b0;stop-opacity:.85"></stop>
      <stop offset="1" style="stop-color:#ffe6b0;stop-opacity:0"></stop>
    </radialGradient>
    <!-- leaves are inlined as direct paths below (cascade-safe var fills) -->
    <g id="ban" data-mk="banana">
      <path d="M -13 24 C -25 8 -22 -18 -6 -30 C 0 -34 7 -31 6 -24 C -3 -14 -5 6 5 20 C 10 27 2 32 -13 24 Z" style="fill:var(--banana,#ffd23f)"></path>
      <path d="M -9 20 C -18 6 -15 -14 -4 -24 C -1 -27 2 -26 1 -22 C -6 -12 -7 6 1 17 C 4 21 -2 24 -9 20 Z" style="fill:var(--banana-2,#ffe884);opacity:.85"></path>
      <path d="M -13 24 C -18 27 -22 26 -22 22 C -21 20 -17 21 -13 24 Z" style="fill:var(--banana-tip,#7a5a2a)"></path>
      <rect x="3" y="-33" width="5" height="9" rx="2.4" transform="rotate(18 5 -30)" style="fill:var(--banana-stem,#5f7a2a)"></rect>
    </g>
  </defs>

  <!-- SKY handled by root-div CSS gradient (cascade-safe) -->

  <!-- STARS (night) -->
  <g data-scif="isNight">
    <g data-mk="stars" style="fill:var(--star,#eaf0ff)">
      <circle cx="180" cy="90" r="2.4" style="animation:mkTwinkle 2.7s ease-in-out infinite"></circle>
      <circle cx="330" cy="150" r="1.8" style="animation:mkTwinkle 3.2s ease-in-out .5s infinite"></circle>
      <circle cx="470" cy="70" r="2.2" style="animation:mkTwinkle 2.3s ease-in-out .9s infinite"></circle>
      <circle cx="620" cy="120" r="1.6" style="animation:mkTwinkle 3s ease-in-out .3s infinite"></circle>
      <circle cx="560" cy="55" r="2" style="animation:mkTwinkle 2.6s ease-in-out 1.1s infinite"></circle>
      <circle cx="760" cy="80" r="2.5" style="animation:mkTwinkle 2.9s ease-in-out .7s infinite"></circle>
      <circle cx="1040" cy="70" r="2" style="animation:mkTwinkle 2.4s ease-in-out 1.3s infinite"></circle>
      <circle cx="1130" cy="140" r="1.8" style="animation:mkTwinkle 3.1s ease-in-out .2s infinite"></circle>
      <circle cx="250" cy="220" r="1.6" style="animation:mkTwinkle 2.8s ease-in-out 1s infinite"></circle>
      <circle cx="1090" cy="230" r="2.2" style="animation:mkTwinkle 2.5s ease-in-out .4s infinite"></circle>
      <circle cx="400" cy="200" r="1.5" style="animation:mkTwinkle 3.3s ease-in-out .8s infinite"></circle>
      <circle cx="880" cy="55" r="1.7" style="animation:mkTwinkle 2.7s ease-in-out 1.5s infinite"></circle>
    </g>
  </g>

  <!-- CELESTIAL: sun (day) / moon (night) -->
  <g data-mk="celestial">
    <g style="animation:mkGlow 6s ease-in-out infinite;transform-origin:930px 172px">
      <circle cx="930" cy="172" r="120" style="fill:var(--celest-glow,#ffe9a8);opacity:.16"></circle>
      <circle cx="930" cy="172" r="92" style="fill:var(--celest-glow,#ffe9a8);opacity:.22"></circle>
      <circle cx="930" cy="172" r="70" style="fill:var(--celest-glow,#ffe9a8);opacity:.32"></circle>
    </g>
    <circle cx="930" cy="172" r="54" style="fill:var(--celest,#fff3c4)"></circle>
    <g data-scif="isNight">
      <g data-mk="moon" style="fill:var(--moon-crater,#d7e0ff);opacity:.5">
        <circle cx="915" cy="160" r="9"></circle>
        <circle cx="948" cy="182" r="12"></circle>
        <circle cx="922" cy="192" r="6"></circle>
      </g>
    </g>
  </g>

  <!-- LIGHT RAYS (morning/day) -->
  <g data-scif="isDay">
    <g data-mk="rays" style="fill:var(--ray,#fff6d8);mix-blend-mode:soft-light">
      <path d="M900 60 L1010 60 L720 620 L560 620 Z" style="opacity:.5;animation:mkRay 7s ease-in-out infinite"></path>
      <path d="M1000 60 L1070 60 L860 620 L740 620 Z" style="opacity:.4;animation:mkRay 9s ease-in-out 1s infinite"></path>
      <path d="M820 60 L880 60 L560 620 L450 620 Z" style="opacity:.35;animation:mkRay 8s ease-in-out .5s infinite"></path>
    </g>
  </g>

  <!-- MIST bands -->
  <g style="fill:var(--mist,#ffffff)">
    <ellipse cx="360" cy="410" rx="380" ry="34" style="opacity:var(--mist-a,.5)"></ellipse>
    <ellipse cx="860" cy="440" rx="420" ry="30" style="opacity:var(--mist-a,.5)"></ellipse>
    <ellipse cx="600" cy="470" rx="520" ry="26" style="opacity:var(--mist-a,.5)"></ellipse>
  </g>

  <!-- FAR CANOPY silhouettes (background trees, depth 1) -->
  <g data-mk="bg-far" style="fill:var(--canopy-far,#cfe6c9)">
    <ellipse cx="110" cy="380" rx="150" ry="120"></ellipse>
    <ellipse cx="260" cy="360" rx="130" ry="140"></ellipse>
    <ellipse cx="1000" cy="370" rx="150" ry="130"></ellipse>
    <ellipse cx="1150" cy="390" rx="130" ry="120"></ellipse>
  </g>
  <g data-mk="bg-far2" style="fill:var(--canopy-far-2,#bcdcc0)">
    <ellipse cx="180" cy="410" rx="120" ry="100"></ellipse>
    <ellipse cx="1080" cy="415" rx="120" ry="100"></ellipse>
    <ellipse cx="330" cy="430" rx="90" ry="80"></ellipse>
    <ellipse cx="900" cy="430" rx="90" ry="80"></ellipse>
  </g>

  <!-- MID trees (depth 2): palms + broadleaf, sides only, center kept open -->
  <g data-mk="bg-mid" style="fill:var(--canopy-mid,#8fc98a)">
    <!-- left palm -->
    <path d="M150 560 C 146 480 150 420 158 372 L172 372 C 178 430 176 500 172 560 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <g style="transform-origin:165px 372px;animation:mkSwayA 6.5s ease-in-out infinite">
      <path d="M165 372 C 110 350 70 356 40 380 C 78 356 128 356 165 372 Z" style="fill:var(--canopy-mid-2,#79bd82)"></path>
      <path d="M165 372 C 108 356 66 380 46 420 C 96 380 132 366 165 372 Z"></path>
      <path d="M165 372 C 220 350 262 356 292 380 C 254 356 202 356 165 372 Z" style="fill:var(--canopy-mid-2,#79bd82)"></path>
      <path d="M165 372 C 222 356 264 380 284 420 C 234 380 198 366 165 372 Z"></path>
      <path d="M165 372 C 158 320 160 292 170 262 C 178 300 176 340 172 372 Z"></path>
    </g>
    <!-- left broadleaf tree -->
    <path d="M330 570 C 326 500 330 452 336 412 L350 412 C 356 460 354 520 350 570 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <ellipse cx="343" cy="392" rx="86" ry="72" style="fill:var(--canopy-mid,#8fc98a)"></ellipse>
    <ellipse cx="300" cy="410" rx="54" ry="46" style="fill:var(--canopy-mid-2,#79bd82)"></ellipse>
    <ellipse cx="388" cy="410" rx="54" ry="46" style="fill:var(--canopy-mid-2,#79bd82)"></ellipse>
    <!-- right palm -->
    <path d="M980 560 C 976 480 980 420 988 372 L1002 372 C 1008 430 1006 500 1002 560 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <g style="transform-origin:995px 372px;animation:mkSwayB 7s ease-in-out infinite">
      <path d="M995 372 C 940 350 900 356 870 380 C 908 356 958 356 995 372 Z" style="fill:var(--canopy-mid-2,#79bd82)"></path>
      <path d="M995 372 C 938 356 896 380 876 420 C 926 380 962 366 995 372 Z"></path>
      <path d="M995 372 C 1050 350 1092 356 1122 380 C 1084 356 1032 356 995 372 Z" style="fill:var(--canopy-mid-2,#79bd82)"></path>
      <path d="M995 372 C 1052 356 1094 380 1114 420 C 1064 380 1028 366 995 372 Z"></path>
      <path d="M995 372 C 988 320 990 292 1000 262 C 1008 300 1006 340 1002 372 Z"></path>
    </g>
    <!-- right broadleaf tree -->
    <path d="M1080 570 C 1076 500 1080 452 1086 412 L1100 412 C 1106 460 1104 520 1100 570 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <ellipse cx="1093" cy="392" rx="82" ry="70" style="fill:var(--canopy-mid,#8fc98a)"></ellipse>
    <ellipse cx="1052" cy="410" rx="50" ry="44" style="fill:var(--canopy-mid-2,#79bd82)"></ellipse>
    <ellipse cx="1134" cy="410" rx="50" ry="44" style="fill:var(--canopy-mid-2,#79bd82)"></ellipse>
    <!-- distant center shrub (kept low, sky stays open above) -->
    <ellipse cx="740" cy="452" rx="70" ry="46" style="fill:var(--canopy-mid-2,#79bd82)"></ellipse>
  </g>

  <!-- BACK GROUND mound -->
  <path d="M0 560 C 260 520 460 560 640 556 C 860 552 1040 520 1200 552 L1200 760 L0 760 Z" style="fill:var(--ground-2,#6aa85c)"></path>

  <!-- HANGING VINES -->
  <g data-mk="vines" style="stroke:var(--vine,#4f9a4a);stroke-width:7;fill:none;stroke-linecap:round">
    <g style="transform-origin:360px 120px;animation:mkVine 6s ease-in-out infinite">
      <path d="M360 120 C 350 220 372 320 356 430"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(356 432) rotate(150) scale(.55)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(368 340) rotate(122) scale(.44)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(360 250) rotate(-150) scale(.4)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
    </g>
    <g style="transform-origin:690px 108px;animation:mkVine 7.4s ease-in-out .6s infinite">
      <path d="M690 108 C 700 210 682 300 700 402"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(700 404) rotate(205) scale(.55)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(688 310) rotate(232) scale(.44)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(694 220) rotate(200) scale(.4)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
    </g>
    <g style="transform-origin:860px 140px;animation:mkVine 6.8s ease-in-out 1.2s infinite">
      <path d="M860 140 C 872 240 852 340 872 470"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(872 472) rotate(160) scale(.52)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(858 370) rotate(140) scale(.42)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
      <path d="M0 0 C -27 -16 -24 -54 0 -74 C 24 -54 27 -16 0 0 Z" transform="translate(866 264) rotate(172) scale(.38)" style="fill:var(--vine,#4f9a4a);stroke:none"></path>
    </g>
  </g>

  <!-- HERO TREE: trunk + branches -->
  <g data-mk="tree">
    <!-- trunk -->
    <path d="M486 726 C 500 636 512 560 528 486 C 540 430 556 372 590 330 L648 344 C 616 392 600 452 592 512 C 582 596 596 664 616 726 Z" style="fill:var(--trunk,#b07a45)"></path>
    <!-- trunk shadow side -->
    <path d="M486 726 C 500 636 512 560 528 486 C 538 436 552 384 578 344 C 566 392 556 452 552 512 C 546 600 556 668 566 726 Z" style="fill:var(--trunk-2,#8f5f33);opacity:.8"></path>
    <!-- trunk rim light -->
    <path d="M602 336 C 626 372 616 452 610 512 C 602 596 612 664 626 720" style="fill:none;stroke:var(--trunk-rim,#d6a56a);stroke-width:6;stroke-linecap:round;opacity:.7"></path>
    <!-- root flares -->
    <path d="M486 726 C 470 700 452 694 430 700 C 456 706 472 716 486 726 Z" style="fill:var(--trunk,#b07a45)"></path>
    <path d="M616 726 C 636 702 660 696 684 704 C 656 710 636 718 616 726 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <!-- bark lines -->
    <path d="M534 470 C 548 400 566 366 592 340 M556 560 C 560 500 566 452 578 410" style="fill:none;stroke:var(--trunk-dark,#6f4a28);stroke-width:3;stroke-linecap:round;opacity:.5"></path>
    <!-- branches -->
    <path d="M582 356 C 520 320 452 300 392 306 C 456 316 520 336 578 372 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
    <path d="M602 332 C 664 300 736 292 800 306 C 736 312 668 330 616 362 Z" style="fill:var(--trunk,#b07a45)"></path>
    <path d="M600 320 C 604 260 598 210 610 168 C 620 214 616 276 616 330 Z" style="fill:var(--trunk-2,#8f5f33)"></path>
  </g>

  <!-- CANOPY: banana-tree crown of 89 radiating fronds (covers branches) -->
  <g data-mk="canopy-back">
    <g style="transform-origin:600px 322px;animation:mkSwayB 8s ease-in-out infinite">
      <ellipse cx="600" cy="258" rx="21" ry="82" transform="rotate(-150 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="249" rx="26" ry="93" transform="rotate(-134 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="255" rx="25" ry="86" transform="rotate(-118 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="246" rx="24" ry="97" transform="rotate(-102 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="252" rx="23" ry="90" transform="rotate(-88 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="257" rx="22" ry="83" transform="rotate(-74 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="249" rx="21" ry="94" transform="rotate(-60 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="254" rx="26" ry="87" transform="rotate(-46 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="246" rx="25" ry="98" transform="rotate(-32 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="251" rx="24" ry="91" transform="rotate(-18 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="256" rx="23" ry="84" transform="rotate(-4 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="248" rx="22" ry="95" transform="rotate(10 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="253" rx="21" ry="88" transform="rotate(24 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="245" rx="26" ry="99" transform="rotate(38 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="250" rx="25" ry="92" transform="rotate(52 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="256" rx="24" ry="85" transform="rotate(66 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="247" rx="23" ry="96" transform="rotate(80 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="253" rx="22" ry="89" transform="rotate(94 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="258" rx="21" ry="82" transform="rotate(108 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="249" rx="26" ry="93" transform="rotate(122 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="255" rx="25" ry="86" transform="rotate(136 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="246" rx="24" ry="97" transform="rotate(150 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="230" rx="24" ry="110" transform="rotate(-94 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="230" rx="24" ry="110" transform="rotate(-84 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="230" rx="24" ry="110" transform="rotate(84 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="600" cy="230" rx="24" ry="110" transform="rotate(94 600 322)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="405" cy="262" rx="16" ry="56" transform="rotate(-150 405 300)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="405" cy="262" rx="16" ry="63" transform="rotate(-128 405 300)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="795" cy="267" rx="16" ry="56" transform="rotate(150 795 305)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
      <ellipse cx="795" cy="267" rx="16" ry="63" transform="rotate(128 795 305)" style="fill:var(--leaf-dark,#3f8f43)"></ellipse>
    </g>
    <g style="transform-origin:600px 322px;animation:mkSwayA 6.6s ease-in-out infinite">
      <ellipse cx="600" cy="269" rx="18" ry="66" transform="rotate(-142 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="259" rx="22" ry="79" transform="rotate(-126 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="263" rx="20" ry="74" transform="rotate(-110 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="267" rx="18" ry="69" transform="rotate(-96 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="256" rx="22" ry="82" transform="rotate(-82 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="260" rx="20" ry="77" transform="rotate(-68 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="264" rx="18" ry="72" transform="rotate(-54 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="268" rx="22" ry="67" transform="rotate(-40 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="258" rx="20" ry="80" transform="rotate(-26 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="262" rx="18" ry="75" transform="rotate(-12 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="266" rx="22" ry="70" transform="rotate(2 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="256" rx="20" ry="83" transform="rotate(16 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="260" rx="18" ry="78" transform="rotate(30 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="264" rx="22" ry="73" transform="rotate(44 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="268" rx="20" ry="68" transform="rotate(58 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="257" rx="18" ry="81" transform="rotate(72 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="261" rx="22" ry="76" transform="rotate(86 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="265" rx="20" ry="71" transform="rotate(100 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="269" rx="18" ry="66" transform="rotate(114 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="259" rx="22" ry="79" transform="rotate(128 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="263" rx="20" ry="74" transform="rotate(142 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(-48 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(-26 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(-8 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(8 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(26 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="600" cy="280" rx="17" ry="58" transform="rotate(48 600 322)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="405" cy="262" rx="16" ry="58" transform="rotate(-106 405 300)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="405" cy="262" rx="16" ry="65" transform="rotate(-86 405 300)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="405" cy="262" rx="16" ry="60" transform="rotate(-66 405 300)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="795" cy="267" rx="16" ry="58" transform="rotate(106 795 305)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="795" cy="267" rx="16" ry="65" transform="rotate(86 795 305)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="795" cy="267" rx="16" ry="60" transform="rotate(66 795 305)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="608" cy="148" rx="15" ry="52" transform="rotate(-38 608 178)" style="fill:var(--leaf,#6bbf59)"></ellipse>
      <ellipse cx="608" cy="148" rx="15" ry="52" transform="rotate(-18 608 178)" style="fill:var(--leaf,#6bbf59)"></ellipse>
    </g>
  </g>

  <!-- BANANAS: bunch nestled in the canopy + flower bud -->
  <g data-scif="showBananas"><g data-mk="bananas">
    <path d="M600 292 C 606 320 606 360 604 404" style="fill:none;stroke:var(--trunk-2,#8f5f33);stroke-width:9;stroke-linecap:round"></path>
    <g data-mk-banana="1" style="display:none;transform-box:fill-box;transform-origin:566px 316px"><use href="#ban" transform="translate(566 316) rotate(-48) scale(1.15)"></use></g>
    <g data-mk-banana="2" style="display:none;transform-box:fill-box;transform-origin:598px 322px"><use href="#ban" transform="translate(598 322) rotate(-18) scale(1.2)"></use></g>
    <g data-mk-banana="3" style="display:none;transform-box:fill-box;transform-origin:628px 317px"><use href="#ban" transform="translate(628 317) rotate(18) scale(1.16)"></use></g>
    <g data-mk-banana="4" style="display:none;transform-box:fill-box;transform-origin:652px 305px"><use href="#ban" transform="translate(652 305) rotate(44) scale(1.1)"></use></g>
    <g data-mk-banana="5" style="display:none;transform-box:fill-box;transform-origin:572px 348px"><use href="#ban" transform="translate(572 348) rotate(-40) scale(1.17)"></use></g>
    <g data-mk-banana="6" style="display:none;transform-box:fill-box;transform-origin:606px 356px"><use href="#ban" transform="translate(606 356) rotate(-8) scale(1.22)"></use></g>
    <g data-mk-banana="7" style="display:none;transform-box:fill-box;transform-origin:636px 348px"><use href="#ban" transform="translate(636 348) rotate(28) scale(1.15)"></use></g>
    <g data-mk-banana="8" style="display:none;transform-box:fill-box;transform-origin:586px 382px"><use href="#ban" transform="translate(586 382) rotate(-32) scale(1.15)"></use></g>
    <g data-mk-banana="9" style="display:none;transform-box:fill-box;transform-origin:620px 382px"><use href="#ban" transform="translate(620 382) rotate(10) scale(1.17)"></use></g>
    <g data-mk-banana="10" style="display:none;transform-box:fill-box;transform-origin:604px 408px"><use href="#ban" transform="translate(604 408) rotate(-8) scale(1.12)"></use></g>
    <path d="M604 404 C 620 410 626 430 618 448 C 612 460 596 460 590 448 C 582 430 588 410 604 404 Z" style="fill:#7d3a63"></path>
    <path d="M604 410 C 615 414 619 429 613 443 C 609 451 599 451 595 443 C 589 429 593 414 604 410 Z" style="fill:#9a4a7a"></path>
    <path d="M595 446 C 599 456 609 456 613 446 C 617 452 614 463 604 467 C 594 463 591 452 595 446 Z" style="fill:#6a3054"></path>
  </g></g>

  <g data-mk="canopy-front">
    <g style="transform-origin:600px 316px;animation:mkSwayB 7.4s ease-in-out .4s infinite">
      <ellipse cx="600" cy="280" rx="15" ry="54" transform="rotate(-84 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="273" rx="19" ry="63" transform="rotate(-70 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="278" rx="18" ry="56" transform="rotate(-56 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="271" rx="17" ry="65" transform="rotate(-42 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="277" rx="16" ry="58" transform="rotate(-30 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="270" rx="15" ry="67" transform="rotate(-18 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="275" rx="19" ry="60" transform="rotate(-6 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="268" rx="18" ry="69" transform="rotate(6 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="274" rx="17" ry="62" transform="rotate(18 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="279" rx="16" ry="55" transform="rotate(30 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="272" rx="15" ry="64" transform="rotate(42 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="278" rx="19" ry="57" transform="rotate(56 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="271" rx="18" ry="66" transform="rotate(70 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="276" rx="17" ry="59" transform="rotate(84 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="284" rx="15" ry="50" transform="rotate(-32 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="284" rx="15" ry="50" transform="rotate(-14 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="284" rx="15" ry="50" transform="rotate(0 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="284" rx="15" ry="50" transform="rotate(14 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="600" cy="284" rx="15" ry="50" transform="rotate(32 600 322)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="405" cy="270" rx="14" ry="48" transform="rotate(-112 405 300)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="795" cy="275" rx="14" ry="48" transform="rotate(112 795 305)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="608" cy="148" rx="15" ry="52" transform="rotate(0 608 178)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="608" cy="148" rx="15" ry="52" transform="rotate(18 608 178)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
      <ellipse cx="608" cy="148" rx="15" ry="52" transform="rotate(38 608 178)" style="fill:var(--leaf-3,#84cf6b)"></ellipse>
    </g>
  </g>

  <!-- FRONT GROUND mound (monkey stands here) -->
  <path d="M0 636 C 240 604 440 640 640 636 C 880 632 1020 604 1200 632 L1200 760 L0 760 Z" style="fill:var(--ground,#7bb86a)"></path>
  <path d="M0 636 C 240 604 440 640 640 636 C 880 632 1020 604 1200 632" style="fill:none;stroke:var(--ground-rim,#96d17e);stroke-width:5;opacity:.6"></path>

  <!-- warm character glow (night) -->
  <ellipse cx="470" cy="600" rx="260" ry="220" fill="url(#mkWarmGlow)" style="opacity:var(--glow-a,0)"></ellipse>

  <!-- baked monkey omitted: the game overlays the interactive Monkey character -->

  <!-- FOREGROUND plants (in front of monkey) -->
  <g data-mk="foreground">
    <!-- bottom-left monstera -->
    <g style="fill:var(--fg-leaf,#2f7a3a);transform-origin:120px 760px;animation:mkSwayA 7.6s ease-in-out infinite">
      <path d="M120 760 C 40 720 6 640 30 560 C 70 600 96 620 120 616 C 96 640 96 700 120 760 Z"></path>
      <path d="M150 760 C 210 726 250 660 236 588 C 200 622 172 636 150 632 C 172 660 176 706 150 760 Z" style="fill:var(--fg-leaf-2,#1f5f2c)"></path>
    </g>
    <!-- bottom-left fern fronds -->
    <g style="fill:var(--fg-leaf-2,#1f5f2c);transform-origin:280px 760px;animation:mkSwayB 6.8s ease-in-out .5s infinite">
      <path d="M280 760 C 258 690 262 626 292 578 C 288 636 296 700 312 760 Z"></path>
      <path d="M300 760 C 300 700 318 648 356 610 C 330 656 322 706 330 760 Z" style="fill:var(--fg-leaf,#2f7a3a)"></path>
    </g>
    <!-- bottom-right elephant ear -->
    <g style="fill:var(--fg-leaf,#2f7a3a);transform-origin:1090px 760px;animation:mkSwayA 8.2s ease-in-out .3s infinite">
      <path d="M1090 760 C 1180 726 1216 646 1192 566 C 1150 606 1120 622 1094 618 C 1120 644 1120 702 1090 760 Z"></path>
      <path d="M1058 760 C 990 730 952 664 968 592 C 1006 626 1034 640 1058 636 C 1034 662 1030 706 1058 760 Z" style="fill:var(--fg-leaf-2,#1f5f2c)"></path>
    </g>
    <!-- right sprout -->
    <g style="fill:var(--fg-leaf-2,#1f5f2c);transform-origin:940px 760px;animation:mkSwayB 7.2s ease-in-out .8s infinite">
      <path d="M940 760 C 918 704 924 652 954 614 C 946 664 952 712 968 760 Z"></path>
      <path d="M958 760 C 962 712 984 668 1018 640 C 992 678 984 720 990 760 Z" style="fill:var(--fg-leaf,#2f7a3a)"></path>
    </g>
    <!-- small grass tufts near monkey base -->
    <g style="fill:var(--fg-leaf,#2f7a3a)">
      <path d="M360 720 C 356 700 360 686 372 676 C 368 692 372 708 380 722 Z"></path>
      <path d="M600 726 C 598 706 604 692 616 684 C 610 700 612 714 620 726 Z" style="fill:var(--fg-leaf-2,#1f5f2c)"></path>
    </g>
  </g>

  <!-- BUTTERFLIES (day) -->
  <g data-scif="isDay">
    <g data-mk="butterflies">
      <g style="transform-origin:850px 372px;animation:mkFly1 9s ease-in-out infinite">
        <ellipse cx="840" cy="372" rx="10" ry="13" style="fill:var(--bfly,#e5674f);transform-origin:850px 372px;animation:mkWing .5s ease-in-out infinite"></ellipse>
        <ellipse cx="860" cy="372" rx="10" ry="13" style="fill:var(--bfly-2,#f2a83f);transform-origin:850px 372px;animation:mkWing .5s ease-in-out infinite"></ellipse>
        <rect x="848" y="364" width="4" height="18" rx="2" style="fill:#3a2416"></rect>
      </g>
      <g style="transform-origin:300px 396px;animation:mkFly2 11s ease-in-out 1s infinite">
        <ellipse cx="292" cy="396" rx="8" ry="11" style="fill:var(--bfly-2,#f2a83f);transform-origin:300px 396px;animation:mkWing .45s ease-in-out infinite"></ellipse>
        <ellipse cx="308" cy="396" rx="8" ry="11" style="fill:var(--bfly,#e5674f);transform-origin:300px 396px;animation:mkWing .45s ease-in-out infinite"></ellipse>
        <rect x="298" y="389" width="3.5" height="15" rx="1.8" style="fill:#3a2416"></rect>
      </g>
    </g>
  </g>

  <!-- FIREFLIES (night) -->
  <g data-scif="isNight">
    <g data-mk="fireflies" style="fill:var(--firefly,#fff1a8)">
      <circle cx="300" cy="520" r="4" style="animation:mkFire 5s ease-in-out infinite"></circle>
      <circle cx="700" cy="560" r="3.4" style="animation:mkFire 6.2s ease-in-out .6s infinite"></circle>
      <circle cx="860" cy="470" r="4" style="animation:mkFire 5.6s ease-in-out 1.1s infinite"></circle>
      <circle cx="220" cy="600" r="3" style="animation:mkFire 6.8s ease-in-out .3s infinite"></circle>
      <circle cx="620" cy="430" r="3.6" style="animation:mkFire 5.2s ease-in-out 1.5s infinite"></circle>
      <circle cx="960" cy="580" r="3" style="animation:mkFire 7s ease-in-out .9s infinite"></circle>
      <circle cx="400" cy="470" r="3.4" style="animation:mkFire 6s ease-in-out 1.8s infinite"></circle>
      <circle cx="780" cy="620" r="4" style="animation:mkFire 5.4s ease-in-out .5s infinite"></circle>
      <circle cx="520" cy="600" r="3" style="animation:mkFire 6.6s ease-in-out 1.3s infinite"></circle>
    </g>
  </g>

  <!-- CELEBRATION VINES (Flow; shown during the launch swing) -->
  <g data-mk="celebration-vines" style="display:none">
          <g style="transform-origin:340px 0px;animation:mkVineSway 3.4s ease-in-out infinite">
            <path d="M340 -200 L340 0 C 330 150 352 330 340 480" style="fill:none;stroke:#3f8f43;stroke-width:8;stroke-linecap:round"></path>
          </g>
          <g style="transform-origin:520px 0px;animation:mkVineSway 4s ease-in-out .5s infinite">
            <path d="M520 -200 L520 0 C 532 160 508 340 522 470" style="fill:none;stroke:#4f9a4a;stroke-width:9;stroke-linecap:round"></path>
          </g>
          <g style="transform-origin:720px 0px;animation:mkVineSway 3.7s ease-in-out .3s infinite">
            <path d="M720 -200 L720 0 C 710 160 732 340 720 490" style="fill:none;stroke:#3f8f43;stroke-width:8;stroke-linecap:round"></path>
          </g>
          <g style="transform-origin:900px 0px;animation:mkVineSway 4.2s ease-in-out .8s infinite">
            <path d="M900 -200 L900 0 C 912 150 888 330 904 470" style="fill:none;stroke:#4f9a4a;stroke-width:9;stroke-linecap:round"></path>
          </g>
  </g>
  <!-- MONKEY CHARACTER (Monkey.dc.html; all 5 poses; at the Flow's standing spot) -->
  <g data-mk="monkey-bounce" style="transform-box:fill-box;transform-origin:50% 60%">
    <svg data-mk="monkey-char" x="750" y="285" width="276" height="349.6" viewBox="0 0 300 380" style="overflow:visible">

  <!-- STANDING POSES (content / delight / cheer) share a base -->
  <g data-mk="pose-standing">
   <g style="transform-origin:150px 352px;animation:mkbBob 4.6s ease-in-out infinite">
    <ellipse cx="150" cy="364" rx="80" ry="14" style="fill:var(--char-shadow,rgba(40,60,30,.2))"></ellipse>
    <!-- tail -->
    <g style="transform-origin:112px 300px;animation:mkbTail 5s ease-in-out infinite">
      <path d="M116 300 C 66 316 28 298 18 256 C 12 224 30 200 60 202 C 38 210 34 232 46 250 C 60 270 92 274 122 280 Z" style="fill:var(--fur,#b57a45)"></path>
      <path d="M116 298 C 74 312 42 298 30 264" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:4;stroke-linecap:round;opacity:.55"></path>
    </g>
    <!-- legs + feet -->
    <path d="M112 286 C 104 326 104 344 108 352 L146 352 C 144 336 142 312 146 286 Z" style="fill:var(--fur,#b57a45)"></path>
    <path d="M156 286 C 160 326 164 342 170 352 L206 352 C 202 334 194 312 190 286 Z" style="fill:var(--fur-2,#96602f)"></path>
    <ellipse cx="122" cy="356" rx="27" ry="13" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
    <ellipse cx="182" cy="356" rx="27" ry="13" style="fill:var(--fur-face-2,#e0bd8c)"></ellipse>
    <!-- body -->
    <ellipse cx="150" cy="264" rx="63" ry="66" style="fill:var(--fur,#b57a45)"></ellipse>
    <ellipse cx="150" cy="276" rx="43" ry="50" style="fill:var(--fur-face,#f0d3a8)"></ellipse>

    <!-- ARMS: content -->
    <g data-mk="arms-content" style="display:none">
      <path d="M100 236 C 86 258 92 282 114 290 C 122 278 132 268 142 262 Z" style="fill:var(--fur-2,#96602f)"></path>
      <path d="M200 236 C 214 258 208 282 186 290 C 178 278 168 268 158 262 Z" style="fill:var(--fur,#b57a45)"></path>
      <ellipse cx="126" cy="288" rx="14" ry="12" style="fill:var(--fur-face-2,#e0bd8c)"></ellipse>
      <ellipse cx="174" cy="288" rx="14" ry="12" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
    </g>
    <!-- ARMS: delight (raised, open hands) -->
    <g data-mk="arms-delight">
      <path d="M112 230 C 92 202 86 152 100 112 C 110 152 124 192 142 216 Z" style="fill:var(--fur-2,#96602f)"></path>
      <path d="M188 230 C 208 202 214 152 200 112 C 190 152 176 192 158 216 Z" style="fill:var(--fur,#b57a45)"></path>
      <circle cx="98" cy="104" r="15" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="202" cy="104" r="15" style="fill:var(--fur-face,#f0d3a8)"></circle>
      <path d="M91 99 q7 -5 14 0 M91 106 q7 -4 14 0" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:1.8;stroke-linecap:round;opacity:.45"></path>
      <path d="M195 99 q7 -5 14 0 M195 106 q7 -4 14 0" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:1.8;stroke-linecap:round;opacity:.3"></path>
    </g>
    <!-- ARMS: cheer (triumphant fists up) -->
    <g data-mk="arms-cheer" style="display:none">
      <path d="M108 234 C 86 214 80 178 100 150 C 108 176 124 200 138 218 Z" style="fill:var(--fur-2,#96602f)"></path>
      <path d="M192 234 C 214 214 220 178 200 150 C 192 176 176 200 162 218 Z" style="fill:var(--fur,#b57a45)"></path>
      <circle cx="98" cy="146" r="17" style="fill:var(--fur,#b57a45)"></circle>
      <circle cx="202" cy="146" r="17" style="fill:var(--fur-2,#96602f)"></circle>
      <path d="M86 142 q12 -5 24 0 M88 150 q10 -4 20 0" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:2.4;stroke-linecap:round;opacity:.7"></path>
      <path d="M190 142 q12 -5 24 0 M192 150 q10 -4 20 0" style="fill:none;stroke:var(--fur-face,#f0d3a8);stroke-width:2.4;stroke-linecap:round;opacity:.5"></path>
    </g>
    <!-- ARMS: eat (hands up to mouth) -->
    <g data-mk="arms-eat" style="display:none">
      <path d="M110 232 C 94 210 96 178 116 160 C 122 180 132 200 146 216 Z" style="fill:var(--fur-2,#96602f)"></path>
      <path d="M190 232 C 206 210 204 178 184 160 C 178 180 168 200 154 216 Z" style="fill:var(--fur,#b57a45)"></path>
      <circle cx="122" cy="152" r="14" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="178" cy="152" r="14" style="fill:var(--fur-face,#f0d3a8)"></circle>
    </g>

    <!-- HEAD base -->
    <g data-mk="head">
      <circle cx="92" cy="146" r="24" style="fill:var(--fur,#b57a45)"></circle>
      <circle cx="92" cy="146" r="13" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="208" cy="146" r="24" style="fill:var(--fur,#b57a45)"></circle>
      <circle cx="208" cy="146" r="13" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="150" cy="150" r="64" style="fill:var(--fur,#b57a45)"></circle>
      <path d="M150 106 C 190 106 214 136 214 172 C 214 208 186 232 150 232 C 114 232 86 208 86 172 C 86 136 110 106 150 106 Z" style="fill:var(--fur-face,#f0d3a8)"></path>
      <path d="M202 114 C 222 132 228 158 224 186" style="fill:none;stroke:var(--fur-rim,#fff0c0);stroke-width:6;stroke-linecap:round;opacity:.7"></path>
      <ellipse cx="150" cy="196" rx="29" ry="22" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
      <ellipse cx="150" cy="185" rx="7.5" ry="5.5" style="fill:var(--nose,#6f4a2c)"></ellipse>
      <circle cx="112" cy="188" r="9" style="fill:var(--cheek,#f2a37a);opacity:.5"></circle>
      <circle cx="188" cy="188" r="9" style="fill:var(--cheek,#f2a37a);opacity:.5"></circle>

      <!-- EXPRESSION: content -->
      <g data-mk="expr-content" style="display:none">
        <path d="M120 143 Q131 138 142 143 M158 143 Q169 138 180 143" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:3.4;stroke-linecap:round"></path>
        <g style="transform-origin:150px 160px;animation:mkbBlink 6s ease-in-out infinite">
          <ellipse cx="131" cy="160" rx="12" ry="14" style="fill:var(--eye-white,#fffaf0)"></ellipse>
          <ellipse cx="169" cy="160" rx="12" ry="14" style="fill:var(--eye-white,#fffaf0)"></ellipse>
          <circle cx="132" cy="163" r="9" style="fill:var(--eye,#3a2416)"></circle>
          <circle cx="168" cy="163" r="9" style="fill:var(--eye,#3a2416)"></circle>
          <circle cx="135" cy="159" r="3.4" style="fill:#fff"></circle>
          <circle cx="171" cy="159" r="3.4" style="fill:#fff"></circle>
        </g>
        <path d="M132 200 Q150 213 168 200" style="fill:none;stroke:var(--mouth,#7a3f2a);stroke-width:4;stroke-linecap:round"></path>
      </g>
      <!-- EXPRESSION: delight -->
      <g data-mk="expr-delight">
        <path d="M118 136 Q131 129 144 136 M156 136 Q169 129 182 136" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:3.4;stroke-linecap:round"></path>
        <g style="transform-origin:150px 158px;animation:mkbBlink 5s ease-in-out infinite">
          <ellipse cx="130" cy="158" rx="16" ry="19" style="fill:var(--eye-white,#fffaf0)"></ellipse>
          <ellipse cx="170" cy="158" rx="16" ry="19" style="fill:var(--eye-white,#fffaf0)"></ellipse>
          <circle cx="132" cy="161" r="11" style="fill:var(--eye,#3a2416)"></circle>
          <circle cx="168" cy="161" r="11" style="fill:var(--eye,#3a2416)"></circle>
          <circle cx="136" cy="156" r="4.2" style="fill:#fff"></circle>
          <circle cx="172" cy="156" r="4.2" style="fill:#fff"></circle>
          <circle cx="128" cy="164" r="2" style="fill:#fff;opacity:.7"></circle>
          <circle cx="164" cy="164" r="2" style="fill:#fff;opacity:.7"></circle>
        </g>
        <path d="M132 196 C 142 214 158 214 168 196 C 162 208 138 208 132 196 Z" style="fill:var(--mouth,#7a3f2a)"></path>
        <path d="M138 203 C 144 210 156 210 162 203 C 156 208 144 208 138 203 Z" style="fill:var(--tongue,#e88a7a)"></path>
      </g>
      <!-- EXPRESSION: cheer -->
      <g data-mk="expr-cheer" style="display:none">
        <path d="M114 132 Q130 124 146 132 M154 132 Q170 124 186 132" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:3.4;stroke-linecap:round"></path>
        <path d="M118 160 Q131 146 144 160" style="fill:none;stroke:var(--eye,#3a2416);stroke-width:5;stroke-linecap:round"></path>
        <path d="M156 160 Q169 146 182 160" style="fill:none;stroke:var(--eye,#3a2416);stroke-width:5;stroke-linecap:round"></path>
        <path d="M124 190 C 140 218 160 218 176 190 C 168 212 132 212 124 190 Z" style="fill:var(--mouth,#7a3f2a)"></path>
        <path d="M130 191 C 143 199 157 199 170 191 C 157 196 143 196 130 191 Z" style="fill:#fff"></path>
        <path d="M140 205 C 146 213 154 213 160 205 C 154 211 146 211 140 205 Z" style="fill:var(--tongue,#e88a7a)"></path>
        <g style="fill:var(--spark,#ffd23f)">
          <path d="M74 104 l3 9 l9 3 l-9 3 l-3 9 l-3 -9 l-9 -3 l9 -3 z" style="transform-origin:77px 116px;animation:mkbSpark 1.8s ease-in-out infinite"></path>
          <path d="M226 104 l3 9 l9 3 l-9 3 l-3 9 l-3 -9 l-9 -3 l9 -3 z" style="transform-origin:229px 116px;animation:mkbSpark 2.1s ease-in-out .5s infinite"></path>
          <path d="M96 58 l2.4 7 l7 2.4 l-7 2.4 l-2.4 7 l-2.4 -7 l-7 -2.4 l7 -2.4 z" style="transform-origin:98px 68px;animation:mkbSpark 1.6s ease-in-out .3s infinite"></path>
          <path d="M204 62 l2.4 7 l7 2.4 l-7 2.4 l-2.4 7 l-2.4 -7 l-7 -2.4 l7 -2.4 z" style="transform-origin:206px 72px;animation:mkbSpark 1.9s ease-in-out .8s infinite"></path>
        </g>
      </g>
      <!-- EXPRESSION: eat (open mouth) -->
      <g data-mk="expr-eat" style="display:none">
        <path d="M118 138 Q131 130 144 138 M156 138 Q169 130 182 138" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:3.4;stroke-linecap:round"></path>
        <ellipse cx="131" cy="158" rx="13" ry="15" style="fill:var(--eye-white,#fffaf0)"></ellipse>
        <ellipse cx="169" cy="158" rx="13" ry="15" style="fill:var(--eye-white,#fffaf0)"></ellipse>
        <circle cx="133" cy="160" r="9" style="fill:var(--eye,#3a2416)"></circle>
        <circle cx="167" cy="160" r="9" style="fill:var(--eye,#3a2416)"></circle>
        <circle cx="136" cy="156" r="3.4" style="fill:#fff"></circle>
        <circle cx="170" cy="156" r="3.4" style="fill:#fff"></circle>
        <g data-mk="chomp" style="transform-origin:150px 189px">
          <ellipse cx="150" cy="202" rx="19" ry="18" style="fill:var(--mouth,#7a3f2a)"></ellipse>
          <ellipse cx="150" cy="210" rx="12" ry="8" style="fill:var(--tongue,#e88a7a)"></ellipse>
        </g>
      </g>
    </g>
   </g>
  </g>

  <!-- SWING POSE (one-armed vine swing, mid-grin) -->
  <g data-mk="pose-swing" style="display:none">
   <g style="transform-origin:150px 20px;animation:mkbSwing 3.6s ease-in-out infinite">
    <!-- vine -->
    <path d="M150 8 C 146 40 156 66 150 94" style="fill:none;stroke:var(--vine,#4f9a4a);stroke-width:8;stroke-linecap:round"></path>
    <path d="M150 30 C 138 24 130 30 128 40 C 138 42 148 38 152 30 Z" style="fill:var(--vine,#4f9a4a)"></path>
    <!-- tail streaming -->
    <path d="M196 250 C 240 244 268 214 262 178 C 258 156 238 150 222 162 C 238 164 244 182 234 196 C 220 214 200 228 180 236 Z" style="fill:var(--fur,#b57a45)"></path>
    <!-- gripping right arm up to vine -->
    <path d="M150 96 C 152 128 150 156 140 182 C 128 176 122 150 128 120 C 132 104 140 98 150 96 Z" style="fill:var(--fur-2,#96602f)"></path>
    <circle cx="150" cy="94" r="15" style="fill:var(--fur-face,#f0d3a8)"></circle>
    <path d="M140 90 q10 -6 20 0" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:2.4;stroke-linecap:round;opacity:.6"></path>
    <!-- legs tucked / kicking -->
    <path d="M126 268 C 104 282 92 308 102 330 C 116 322 130 306 142 288 Z" style="fill:var(--fur,#b57a45)"></path>
    <ellipse cx="104" cy="330" rx="20" ry="11" transform="rotate(30 104 330)" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
    <path d="M176 272 C 196 290 200 316 188 336 C 176 326 166 306 160 286 Z" style="fill:var(--fur-2,#96602f)"></path>
    <ellipse cx="190" cy="336" rx="20" ry="11" transform="rotate(-24 190 336)" style="fill:var(--fur-face-2,#e0bd8c)"></ellipse>
    <!-- body (slight tilt) -->
    <g transform="rotate(-7 150 226)">
      <ellipse cx="150" cy="228" rx="60" ry="64" style="fill:var(--fur,#b57a45)"></ellipse>
      <ellipse cx="150" cy="240" rx="41" ry="48" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
    </g>
    <!-- free left arm waving out -->
    <path d="M100 214 C 74 202 60 178 68 154 C 78 172 94 190 116 204 Z" style="fill:var(--fur-2,#96602f)"></path>
    <circle cx="64" cy="150" r="14" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
    <!-- HEAD -->
    <g transform="rotate(-4 150 150)">
      <circle cx="96" cy="146" r="23" style="fill:var(--fur,#b57a45)"></circle>
      <circle cx="96" cy="146" r="12" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="204" cy="146" r="23" style="fill:var(--fur,#b57a45)"></circle>
      <circle cx="204" cy="146" r="12" style="fill:var(--fur-face-2,#e0bd8c)"></circle>
      <circle cx="150" cy="150" r="62" style="fill:var(--fur,#b57a45)"></circle>
      <path d="M150 108 C 189 108 212 137 212 172 C 212 207 185 230 150 230 C 115 230 88 207 88 172 C 88 137 111 108 150 108 Z" style="fill:var(--fur-face,#f0d3a8)"></path>
      <path d="M200 116 C 219 133 225 158 221 185" style="fill:none;stroke:var(--fur-rim,#fff0c0);stroke-width:6;stroke-linecap:round;opacity:.7"></path>
      <path d="M120 138 Q132 131 144 138 M158 138 Q170 131 182 138" style="fill:none;stroke:var(--fur-2,#96602f);stroke-width:3.4;stroke-linecap:round"></path>
      <ellipse cx="132" cy="159" rx="15" ry="18" style="fill:var(--eye-white,#fffaf0)"></ellipse>
      <ellipse cx="170" cy="159" rx="15" ry="18" style="fill:var(--eye-white,#fffaf0)"></ellipse>
      <circle cx="135" cy="161" r="10.5" style="fill:var(--eye,#3a2416)"></circle>
      <circle cx="172" cy="161" r="10.5" style="fill:var(--eye,#3a2416)"></circle>
      <circle cx="139" cy="157" r="4" style="fill:#fff"></circle>
      <circle cx="176" cy="157" r="4" style="fill:#fff"></circle>
      <ellipse cx="150" cy="196" rx="28" ry="21" style="fill:var(--fur-face,#f0d3a8)"></ellipse>
      <ellipse cx="150" cy="185" rx="7.5" ry="5.5" style="fill:var(--nose,#6f4a2c)"></ellipse>
      <circle cx="113" cy="188" r="9" style="fill:var(--cheek,#f2a37a);opacity:.5"></circle>
      <circle cx="187" cy="188" r="9" style="fill:var(--cheek,#f2a37a);opacity:.5"></circle>
      <path d="M130 197 C 140 216 160 216 170 197 C 163 209 137 209 130 197 Z" style="fill:var(--mouth,#7a3f2a)"></path>
      <path d="M137 204 C 143 211 157 211 163 204 C 157 209 143 209 137 204 Z" style="fill:var(--tongue,#e88a7a)"></path>
    </g>
   </g>
  </g>

    </svg>
  </g>
  <!-- FLYING BANANA (grabbed & eaten during the countdown) -->
  <g data-mk="flying-banana" style="display:none"><use href="#ban"></use></g>
  <!-- VIGNETTE (edge-darkening; opacity per palette via --vign-a) -->
  <rect data-mk="vignette" x="0" y="0" width="1200" height="760" fill="url(#mkVignette)" style="opacity:0;pointer-events:none"></rect>
</g>`;
